-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.log_google_jobs_page
(
    page_jobs_error character varying COLLATE pg_catalog."default",
    page_id serial NOT NULL,
    page_metadata jsonb,
    page_search_parameters jsonb,
    page_jobs_count int,
    response_status_code int NOT NULL,
    api_url character varying COLLATE pg_catalog."default" NOT NULL,
    is_job_result boolean,
    jobs_ids character varying[] COLLATE pg_catalog."default",
    page_date date NOT NULL,
    page_timestamp timestamp without time zone NOT NULL,
    CONSTRAINT log_google_jobs_page_pkey PRIMARY KEY (page_id, page_date)
);
END;